#!/usr/bin/env python3
"""
agent/report_publisher.py — Results publisher

Publishes Smoky test results to:
  1. Slack    — natural language report generated by Claude, every run
  2. Teams    — Adaptive Card, @critical smoke failures only (immediate)
  3. Discord  — embed, @critical smoke failures only (immediate) — demo channel
  4. Gmail    — batched digest, non-critical/regression failures (see
                agent/send_digest.py for the periodic flush)
  5. Power BI — JSON push to REST API dataset, every run, includes flakiness
  6. Jira     — comment + status transition

Routing follows spec section 8: severity-routed, not broadcast. A @critical
smoke failure gets an immediate, distinct alert (Slack + Teams + Discord). A
standard regression failure is queued in Redis and rolled up into the next
Gmail digest instead of paging anyone immediately.
"""

import os
import json
import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import requests
from anthropic import Anthropic

logger = logging.getLogger("smoky.publisher")

client = Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
MODEL  = "claude-sonnet-4-6"

SLACK_WEBHOOK  = os.environ["SLACK_WEBHOOK_URL"]
SLACK_CHANNEL  = os.environ.get("SLACK_CHANNEL", "#smoky-results")

TEAMS_WEBHOOK_URL   = os.environ.get("TEAMS_WEBHOOK_URL", "")
DISCORD_WEBHOOK_URL = os.environ.get("DISCORD_WEBHOOK_URL", "")

GMAIL_ADDRESS      = os.environ.get("GMAIL_ADDRESS", "")
GMAIL_APP_PASSWORD = os.environ.get("GMAIL_APP_PASSWORD", "")
GMAIL_DIGEST_TO    = os.environ.get("GMAIL_DIGEST_TO", "")

POWERBI_DATASET    = os.environ.get("POWERBI_DATASET_ID", "")
POWERBI_WORKSPACE  = os.environ.get("POWERBI_WORKSPACE_ID", "")
POWERBI_TOKEN      = os.environ.get("POWERBI_ACCESS_TOKEN", "")

JIRA_BASE_URL  = os.environ["JIRA_BASE_URL"]
JIRA_EMAIL     = os.environ["JIRA_EMAIL"]
JIRA_TOKEN     = os.environ["JIRA_API_TOKEN"]

DIGEST_QUEUE_KEY = "smoky:digest-queue"


class ReportPublisher:

    # -----------------------------------------------------------------------
    # Slack
    # -----------------------------------------------------------------------

    def build_slack_message(self, issue_key: str, summary: str, results: dict) -> str:
        """
        Asks Claude to write a concise, readable Slack report from raw JSON results.
        Claude adds a natural language diagnostic on failure.
        """
        passed   = results.get("passed", 0)
        failed   = results.get("failed", 0)
        total    = passed + failed
        duration = results.get("duration_ms", 0)
        status   = "✅ All passed" if failed == 0 else f"❌ {failed} failed"

        # If there are failures, ask Claude to diagnose
        diagnosis = ""
        if failed > 0:
            scenario_details = json.dumps(results.get("scenarios", []), indent=2)
            resp = client.messages.create(
                model=MODEL,
                max_tokens=300,
                system="You are Smoky, a QA agent. Write a concise 2-3 sentence diagnosis of why tests failed. Be direct and actionable.",
                messages=[{"role": "user", "content": f"Test results:\n{scenario_details}"}],
            )
            diagnosis = f"\n\n*Smoky diagnosis:* {resp.content[0].text.strip()}"

        jira_url  = f"{JIRA_BASE_URL}/browse/{issue_key}"
        report_url = results.get("report_url", "#")

        msg = (
            f"*Smoky* | `{issue_key}` | {summary[:60]}\n"
            f"{'━' * 48}\n"
            f"Status  : {status}\n"
            f"Passed  : {passed}/{total}\n"
            f"Duration: {duration // 1000}s\n"
            f"Env     : {results.get('environment', 'staging')}\n"
        )

        if results.get("scenarios"):
            msg += "\n*Scenarios:*\n"
            for sc in results["scenarios"]:
                icon = "✅" if sc.get("status") == "passed" else "❌"
                msg += f"{icon} {sc.get('name', 'unknown')} — {sc.get('duration_ms', 0) // 1000}s\n"

        msg += diagnosis
        msg += f"\n\n<{jira_url}|Open Jira ticket>  |  <{report_url}|Full report>"

        return msg

    def send_slack(self, message: str) -> bool:
        """Sends the report to the configured Slack channel via webhook."""
        payload = {"channel": SLACK_CHANNEL, "text": message, "mrkdwn": True}
        resp = requests.post(SLACK_WEBHOOK, json=payload)
        if resp.status_code != 200:
            logger.error(f"[slack] Failed: {resp.status_code} — {resp.text}")
            return False
        logger.info("[slack] Report sent")
        return True

    def send_slack_error(self, issue_key: str, error: str, step: str) -> bool:
        """Sends an error alert to Slack when the pipeline fails."""
        msg = (
            f"⚠️ *Smoky pipeline error* | `{issue_key}`\n"
            f"Failed at step: `{step}`\n"
            f"Error: `{error}`\n"
            f"Action needed: check <{JIRA_BASE_URL}/browse/{issue_key}|Jira ticket>"
        )
        return self.send_slack(msg)

    # -----------------------------------------------------------------------
    # Teams — Adaptive Card via a Power Automate workflow webhook (the
    # Office 365 Connector webhook format Teams used previously is
    # deprecated; Adaptive Cards posted to a Workflows HTTP trigger is the
    # current supported path).
    # -----------------------------------------------------------------------

    def send_teams(self, issue_key: str, results: dict) -> bool:
        """Sends an Adaptive Card to Teams. Used for @critical smoke failures only."""
        if not TEAMS_WEBHOOK_URL:
            logger.info("[teams] Skipped — TEAMS_WEBHOOK_URL not configured")
            return False

        passed = results.get("passed", 0)
        failed = results.get("failed", 0)
        status_text = "✅ All passed" if failed == 0 else f"❌ {failed} failed"

        card = {
            "type": "message",
            "attachments": [
                {
                    "contentType": "application/vnd.microsoft.card.adaptive",
                    "content": {
                        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                        "type": "AdaptiveCard",
                        "version": "1.5",
                        "body": [
                            {
                                "type": "TextBlock",
                                "text": f"🚨 Smoky · {issue_key}",
                                "weight": "bolder",
                                "size": "medium",
                            },
                            {"type": "TextBlock", "text": status_text, "wrap": True},
                            {
                                "type": "FactSet",
                                "facts": [
                                    {"title": "Passed", "value": f"{passed}/{passed + failed}"},
                                    {
                                        "title": "Environment",
                                        "value": results.get("environment", "staging"),
                                    },
                                    {
                                        "title": "Duration",
                                        "value": f"{results.get('duration_ms', 0) // 1000}s",
                                    },
                                ],
                            },
                        ],
                        "actions": [
                            {
                                "type": "Action.OpenUrl",
                                "title": "Open report",
                                "url": results.get("report_url", "#"),
                            }
                        ],
                    },
                }
            ],
        }

        resp = requests.post(TEAMS_WEBHOOK_URL, json=card)
        if resp.status_code not in (200, 202):
            logger.error(f"[teams] Failed: {resp.status_code} — {resp.text}")
            return False
        logger.info("[teams] Report sent")
        return True

    # -----------------------------------------------------------------------
    # Discord — demo/portfolio channel, custom webhook embed
    # -----------------------------------------------------------------------

    def send_discord(self, issue_key: str, results: dict) -> bool:
        if not DISCORD_WEBHOOK_URL:
            logger.info("[discord] Skipped — DISCORD_WEBHOOK_URL not configured")
            return False

        passed = results.get("passed", 0)
        failed = results.get("failed", 0)
        color = 0x2ECC71 if failed == 0 else 0xE74C3C  # green / red

        embed = {
            "title": f"Smoky · {issue_key}",
            "description": "✅ All passed" if failed == 0 else f"❌ {failed} failed",
            "color": color,
            "url": results.get("report_url") or None,
            "fields": [
                {"name": "Passed", "value": f"{passed}/{passed + failed}", "inline": True},
                {
                    "name": "Environment",
                    "value": results.get("environment", "staging"),
                    "inline": True,
                },
                {
                    "name": "Duration",
                    "value": f"{results.get('duration_ms', 0) // 1000}s",
                    "inline": True,
                },
            ],
        }
        payload = {"username": "Smoky", "embeds": [embed]}

        resp = requests.post(DISCORD_WEBHOOK_URL, json=payload)
        if resp.status_code not in (200, 204):
            logger.error(f"[discord] Failed: {resp.status_code} — {resp.text}")
            return False
        logger.info("[discord] Report sent")
        return True

    # -----------------------------------------------------------------------
    # Gmail — batched digest, non-technical summary
    # -----------------------------------------------------------------------

    def send_gmail_digest(self, subject: str, runs: list) -> bool:
        """
        Sends a daily/weekly digest summarizing multiple runs in plain
        language. `runs` is a list of results dicts drained from the Redis
        digest queue by agent/send_digest.py.
        """
        if not GMAIL_ADDRESS or not GMAIL_APP_PASSWORD or not GMAIL_DIGEST_TO:
            logger.info("[gmail] Skipped — Gmail digest not configured")
            return False

        total_passed = sum(r.get("passed", 0) for r in runs)
        total_failed = sum(r.get("failed", 0) for r in runs)
        lines = [
            f"Smoky digest — {len(runs)} run(s) since the last summary",
            f"Overall: {total_passed} passed / {total_failed} failed",
            "",
        ]
        for r in runs:
            status = "PASS" if r.get("failed", 0) == 0 else "FAIL"
            total = r.get("passed", 0) + r.get("failed", 0)
            lines.append(
                f"  [{status}] {r.get('issue_key', '?')} — "
                f"{r.get('passed', 0)}/{total} passed ({r.get('environment', 'staging')})"
            )

        body = "\n".join(lines)

        msg = MIMEMultipart()
        msg["From"] = GMAIL_ADDRESS
        msg["To"] = GMAIL_DIGEST_TO
        msg["Subject"] = subject
        msg.attach(MIMEText(body, "plain"))

        try:
            with smtplib.SMTP("smtp.gmail.com", 587) as server:
                server.starttls()
                server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
                server.sendmail(GMAIL_ADDRESS, GMAIL_DIGEST_TO.split(","), msg.as_string())
            logger.info("[gmail] Digest sent")
            return True
        except Exception as e:
            logger.error(f"[gmail] Failed: {e}")
            return False

    # -----------------------------------------------------------------------
    # Severity-routed escalation (spec section 8)
    # -----------------------------------------------------------------------

    def escalate(self, issue_key: str, results: dict, is_critical_smoke: bool = False) -> None:
        """
        - @critical smoke failure -> immediate, distinct alert (Slack + Teams
          + Discord), on top of the normal per-run Slack report.
        - standard/regression failure -> queued for the next Gmail digest,
          not paged immediately.
        Passing runs are never escalated — build_slack_message/send_slack
        already reports every run regardless of outcome.
        """
        if results.get("failed", 0) == 0:
            return

        if is_critical_smoke:
            msg = (
                f"🚨 *CRITICAL smoke failure* | `{issue_key}`\n"
                f"{results['failed']} test(s) failed on a @critical path — immediate attention needed.\n"
                f"<{JIRA_BASE_URL}/browse/{issue_key}|Jira ticket>"
            )
            self.send_slack(msg)
            self.send_teams(issue_key, results)
            self.send_discord(issue_key, results)
        else:
            self._queue_for_digest(issue_key, results)

    def _queue_for_digest(self, issue_key: str, results: dict) -> None:
        from agent.flakiness_tracker import get_client

        redis_client = get_client()
        entry = json.dumps({**results, "issue_key": issue_key})
        redis_client.rpush(DIGEST_QUEUE_KEY, entry)
        logger.info(f"[escalate] Queued {issue_key} for next Gmail digest")

    # -----------------------------------------------------------------------
    # Flakiness (spec section 9) — records this run, returns a per-test map
    # -----------------------------------------------------------------------

    def record_flakiness(self, results: dict) -> dict:
        from agent.flakiness_tracker import get_flakiness, record_run_results

        scenarios = results.get("scenarios", [])
        record_run_results(scenarios, run_id=str(results.get("run_id", "")))
        return {sc.get("name", "unknown"): get_flakiness(sc.get("name", "unknown")) for sc in scenarios}

    # -----------------------------------------------------------------------
    # Power BI
    # -----------------------------------------------------------------------

    def push_powerbi(self, issue_key: str, results: dict, avg_flakiness_pct: float = 0.0) -> bool:
        """
        Pushes test results to a Power BI streaming dataset.
        The dataset schema must have columns matching the row dict below.
        """
        if not POWERBI_DATASET or not POWERBI_WORKSPACE:
            logger.info("[powerbi] Skipped — dataset not configured")
            return False

        row = {
            "issue_key":         issue_key,
            "passed":            results.get("passed", 0),
            "failed":            results.get("failed", 0),
            "total":             results.get("passed", 0) + results.get("failed", 0),
            "duration_ms":       results.get("duration_ms", 0),
            "environment":       results.get("environment", "staging"),
            "conclusion":        results.get("conclusion", "unknown"),
            "run_id":            str(results.get("run_id", "")),
            "avg_flakiness_pct": avg_flakiness_pct,
        }

        url = (
            f"https://api.powerbi.com/v1.0/myorg/groups/{POWERBI_WORKSPACE}"
            f"/datasets/{POWERBI_DATASET}/rows"
        )
        headers = {
            "Authorization": f"Bearer {POWERBI_TOKEN}",
            "Content-Type": "application/json",
        }
        resp = requests.post(url, json={"rows": [row]}, headers=headers)
        if resp.status_code not in (200, 204):
            logger.error(f"[powerbi] Failed: {resp.status_code} — {resp.text}")
            return False
        logger.info("[powerbi] Results pushed")
        return True

    # -----------------------------------------------------------------------
    # Jira
    # -----------------------------------------------------------------------

    def update_jira(self, issue_key: str, results: dict) -> bool:
        """Updates the Jira ticket with test results and transitions its status."""
        failed  = results.get("failed", 0)
        passed  = results.get("passed", 0)
        comment = (
            f"Smoky smoke test completed.\n"
            f"Result: {'PASS' if failed == 0 else 'FAIL'} "
            f"({passed} passed, {failed} failed)\n"
            f"Duration: {results.get('duration_ms', 0) // 1000}s\n"
            f"Run ID: {results.get('run_id', 'N/A')}"
        )

        from agent.jira_watcher import add_comment, transition_ticket
        add_comment(issue_key, comment)

        target_status = "Smoke Done" if failed == 0 else "Smoke Failed"
        transition_ticket(issue_key, target_status)
        logger.info(f"[jira] {issue_key} transitioned to '{target_status}'")
        return True

    def update_jira_failed(self, issue_key: str, error: str) -> bool:
        """Transitions the ticket to 'Smoke Failed' and adds an error comment."""
        from agent.jira_watcher import add_comment, transition_ticket
        add_comment(issue_key, f"Smoky pipeline error: {error}")
        transition_ticket(issue_key, "Smoke Failed")
        return True
