#!/usr/bin/env python3
"""
agent/report_publisher.py — Results publisher

Publishes Smoky test results to:
  1. Slack   — natural language report generated by Claude
  2. Power BI — JSON push to REST API dataset
  3. Jira     — comment + status transition
"""

import os
import json
import logging
import requests
from anthropic import Anthropic

logger = logging.getLogger("smoky.publisher")

client = Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
MODEL  = "claude-sonnet-4-6"

SLACK_WEBHOOK  = os.environ["SLACK_WEBHOOK_URL"]
SLACK_CHANNEL  = os.environ.get("SLACK_CHANNEL", "#smoky-results")
POWERBI_DATASET    = os.environ.get("POWERBI_DATASET_ID", "")
POWERBI_WORKSPACE  = os.environ.get("POWERBI_WORKSPACE_ID", "")
POWERBI_TOKEN      = os.environ.get("POWERBI_ACCESS_TOKEN", "")
JIRA_BASE_URL  = os.environ["JIRA_BASE_URL"]
JIRA_EMAIL     = os.environ["JIRA_EMAIL"]
JIRA_TOKEN     = os.environ["JIRA_API_TOKEN"]


class ReportPublisher:

    # -----------------------------------------------------------------------
    # Slack
    # -----------------------------------------------------------------------

    def build_slack_message(self, issue_key: str, summary: str, results: dict) -> str:
        """
        Asks Claude to write a concise, readable Slack report from raw JSON results.
        Claude adds a natural language diagnostic on failure.
        """
        passed   = results.get("passed", 0)
        failed   = results.get("failed", 0)
        total    = passed + failed
        duration = results.get("duration_ms", 0)
        status   = "✅ All passed" if failed == 0 else f"❌ {failed} failed"

        # If there are failures, ask Claude to diagnose
        diagnosis = ""
        if failed > 0:
            scenario_details = json.dumps(results.get("scenarios", []), indent=2)
            resp = client.messages.create(
                model=MODEL,
                max_tokens=300,
                system="You are Smoky, a QA agent. Write a concise 2-3 sentence diagnosis of why tests failed. Be direct and actionable.",
                messages=[{"role": "user", "content": f"Test results:\n{scenario_details}"}],
            )
            diagnosis = f"\n\n*Smoky diagnosis:* {resp.content[0].text.strip()}"

        jira_url  = f"{JIRA_BASE_URL}/browse/{issue_key}"
        report_url = results.get("report_url", "#")

        msg = (
            f"*Smoky* | `{issue_key}` | {summary[:60]}\n"
            f"{'━' * 48}\n"
            f"Status  : {status}\n"
            f"Passed  : {passed}/{total}\n"
            f"Duration: {duration // 1000}s\n"
            f"Env     : {results.get('environment', 'staging')}\n"
        )

        if results.get("scenarios"):
            msg += "\n*Scenarios:*\n"
            for sc in results["scenarios"]:
                icon = "✅" if sc.get("status") == "passed" else "❌"
                msg += f"{icon} {sc.get('name', 'unknown')} — {sc.get('duration_ms', 0) // 1000}s\n"

        msg += diagnosis
        msg += f"\n\n<{jira_url}|Open Jira ticket>  |  <{report_url}|Full report>"

        return msg

    def send_slack(self, message: str) -> bool:
        """Sends the report to the configured Slack channel via webhook."""
        payload = {"channel": SLACK_CHANNEL, "text": message, "mrkdwn": True}
        resp = requests.post(SLACK_WEBHOOK, json=payload)
        if resp.status_code != 200:
            logger.error(f"[slack] Failed: {resp.status_code} — {resp.text}")
            return False
        logger.info("[slack] Report sent")
        return True

    def send_slack_error(self, issue_key: str, error: str, step: str) -> bool:
        """Sends an error alert to Slack when the pipeline fails."""
        msg = (
            f"⚠️ *Smoky pipeline error* | `{issue_key}`\n"
            f"Failed at step: `{step}`\n"
            f"Error: `{error}`\n"
            f"Action needed: check <{JIRA_BASE_URL}/browse/{issue_key}|Jira ticket>"
        )
        return self.send_slack(msg)

    # -----------------------------------------------------------------------
    # Power BI
    # -----------------------------------------------------------------------

    def push_powerbi(self, issue_key: str, results: dict) -> bool:
        """
        Pushes test results to a Power BI streaming dataset.
        The dataset schema must have columns matching the row dict below.
        """
        if not POWERBI_DATASET or not POWERBI_WORKSPACE:
            logger.info("[powerbi] Skipped — dataset not configured")
            return False

        row = {
            "issue_key":    issue_key,
            "passed":       results.get("passed", 0),
            "failed":       results.get("failed", 0),
            "total":        results.get("passed", 0) + results.get("failed", 0),
            "duration_ms":  results.get("duration_ms", 0),
            "environment":  results.get("environment", "staging"),
            "conclusion":   results.get("conclusion", "unknown"),
            "run_id":       str(results.get("run_id", "")),
        }

        url = (
            f"https://api.powerbi.com/v1.0/myorg/groups/{POWERBI_WORKSPACE}"
            f"/datasets/{POWERBI_DATASET}/rows"
        )
        headers = {
            "Authorization": f"Bearer {POWERBI_TOKEN}",
            "Content-Type": "application/json",
        }
        resp = requests.post(url, json={"rows": [row]}, headers=headers)
        if resp.status_code not in (200, 204):
            logger.error(f"[powerbi] Failed: {resp.status_code} — {resp.text}")
            return False
        logger.info("[powerbi] Results pushed")
        return True

    # -----------------------------------------------------------------------
    # Jira
    # -----------------------------------------------------------------------

    def update_jira(self, issue_key: str, results: dict) -> bool:
        """Updates the Jira ticket with test results and transitions its status."""
        failed  = results.get("failed", 0)
        passed  = results.get("passed", 0)
        comment = (
            f"Smoky smoke test completed.\n"
            f"Result: {'PASS' if failed == 0 else 'FAIL'} "
            f"({passed} passed, {failed} failed)\n"
            f"Duration: {results.get('duration_ms', 0) // 1000}s\n"
            f"Run ID: {results.get('run_id', 'N/A')}"
        )

        from agent.jira_watcher import add_comment, transition_ticket
        add_comment(issue_key, comment)

        target_status = "Smoke Done" if failed == 0 else "Smoke Failed"
        transition_ticket(issue_key, target_status)
        logger.info(f"[jira] {issue_key} transitioned to '{target_status}'")
        return True

    def update_jira_failed(self, issue_key: str, error: str) -> bool:
        """Transitions the ticket to 'Smoke Failed' and adds an error comment."""
        from agent.jira_watcher import add_comment, transition_ticket
        add_comment(issue_key, f"Smoky pipeline error: {error}")
        transition_ticket(issue_key, "Smoke Failed")
        return True
